name: engagement_tracker_sdk
description: A professional engagement tracking SDK for Flutter applications
version: 1.0.0
homepage: https://github.com/yourusername/engagement_tracker_sdk

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  encrypt: ^5.0.1
  http: ^0.13.5
  sqflite: ^2.2.0
  path: ^1.8.2
  uuid: ^3.0.7
  crypto: ^3.0.2
  meta: ^1.9.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  test: ^1.24.0